const scenes = [
    {
        "emoji": "👸🏼🐴🌊",
        "who": "Elsa and the Water Nokk",
        "what": "Riding the magic water horse!",
        "where": "There in the Dark Sea!",
        "when": "At night!",
        "why": "To find the truth!",
        "tag": "Elsa and the Water Nokk riding the magic water horse",
        "image": "scene_0.png",
        "sentence": "Elsa and the Water Nokk are riding the magic water horse there in the dark sea at night."
    },
    {
        "emoji": "👩🏻⛄🍂",
        "who": "Anna and Olaf",
        "what": "Walking and playing!",
        "where": "Here in the Enchanted Forest!",
        "when": "In the morning!",
        "why": "Because they are exploring!",
        "tag": "Anna and Olaf walking and playing",
        "image": "scene_1.png",
        "sentence": "Anna and Olaf are walking and playing here in the enchanted forest in the morning."
    },
    {
        "emoji": "👱‍♂️🦌🌲",
        "who": "Kristoff and Sven",
        "what": "Singing a song!",
        "where": "There in the woods!",
        "when": "In the evening!",
        "why": "Because Kristoff feels sad!",
        "tag": "Kristoff and Sven singing a song",
        "image": "scene_2.png",
        "sentence": "Kristoff and Sven are singing a song there in the woods in the evening."
    },
    {
        "emoji": "👸🏼🦎🔥",
        "who": "Elsa and Bruni",
        "what": "Making ice magic!",
        "where": "Here in the forest!",
        "when": "In the afternoon!",
        "why": "To calm the fire spirit!",
        "tag": "Elsa and Bruni making ice magic",
        "image": "scene_3.png",
        "sentence": "Elsa and Bruni are making ice magic here in the forest in the afternoon."
    },
    {
        "emoji": "👸🏼👩🏻🏰",
        "who": "Elsa and Anna",
        "what": "Opening the gates!",
        "where": "Here at the castle!",
        "when": "In the morning!",
        "why": "To let the people in!",
        "tag": "Elsa and Anna opening the gates",
        "image": "scene_4.png",
        "sentence": "Elsa and Anna are opening the gates here at the castle in the morning."
    },
    {
        "emoji": "⛄🍃🍂",
        "who": "Olaf and Gale",
        "what": "Flying in the wind!",
        "where": "There in the sky!",
        "when": "In the afternoon!",
        "why": "Because the wind is playing!",
        "tag": "Olaf and Gale flying in the wind",
        "image": "scene_5.png",
        "sentence": "Olaf and Gale are flying in the wind there in the sky in the afternoon."
    },
    {
        "emoji": "🪨🌲🌳",
        "who": "The Earth Giants",
        "what": "Sleeping by the river!",
        "where": "There in the valley!",
        "when": "At night!",
        "why": "Because they are tired!",
        "tag": "The Earth Giants sleeping by the river",
        "image": "scene_6.png",
        "sentence": "The Earth Giants are sleeping by the river there in the valley at night."
    },
    {
        "emoji": "💂‍♂️🛡️🌲",
        "who": "Lieutenant Mattias",
        "what": "Guarding the forest!",
        "where": "Here in the trees!",
        "when": "In the daytime!",
        "why": "To protect his people!",
        "tag": "Lieutenant Mattias guarding the forest",
        "image": "scene_7.png",
        "sentence": "Lieutenant Mattias is guarding the forest here in the trees in the daytime."
    },
    {
        "emoji": "👑👸🏼🛏️",
        "who": "Queen Iduna and little Elsa",
        "what": "Singing a lullaby!",
        "where": "Here in the bedroom!",
        "when": "At bedtime!",
        "why": "To help Elsa sleep!",
        "tag": "Queen Iduna and little Elsa singing a lullaby",
        "image": "scene_8.png",
        "sentence": "Queen Iduna and little Elsa are singing a lullaby here in the bedroom at bedtime."
    },
    {
        "emoji": "🧌🔮⛰️",
        "who": "Grand Pabbie",
        "what": "Showing magic visions!",
        "where": "There in the troll valley!",
        "when": "At night!",
        "why": "To warn the sisters!",
        "tag": "Grand Pabbie showing magic visions",
        "image": "scene_9.png",
        "sentence": "Grand Pabbie is showing magic visions there in the troll valley at night."
    },
    {
        "emoji": "👸🏼❄️🏔️",
        "who": "Elsa",
        "what": "Building an ice palace!",
        "where": "High there on the mountain!",
        "when": "At sunrise!",
        "why": "To be free!",
        "tag": "Elsa building an ice palace",
        "image": "scene_10.png",
        "sentence": "Elsa is building an ice palace high there on the mountain at sunrise."
    },
    {
        "emoji": "👩🏻👱‍♂️🛶",
        "who": "Anna and Kristoff",
        "what": "Riding in a boat!",
        "where": "Here on the river!",
        "when": "In the daytime!",
        "why": "To find Elsa!",
        "tag": "Anna and Kristoff riding in a boat",
        "image": "scene_11.png",
        "sentence": "Anna and Kristoff are riding in a boat here on the river in the daytime."
    },
    {
        "emoji": "🦌🥕❄️",
        "who": "Sven",
        "what": "Eating a crunchy carrot!",
        "where": "Here in the snow!",
        "when": "In the morning!",
        "why": "Because he is hungry!",
        "tag": "Sven eating a crunchy carrot",
        "image": "scene_12.png",
        "sentence": "Sven is eating a crunchy carrot here in the snow in the morning."
    },
    {
        "emoji": "🛖🧤🧣",
        "who": "Oaken",
        "what": "Selling winter clothes!",
        "where": "Here in his shop!",
        "when": "In the afternoon!",
        "why": "To help travelers!",
        "tag": "Oaken selling winter clothes",
        "image": "scene_13.png",
        "sentence": "Oaken is selling winter clothes here in his shop in the afternoon."
    },
    {
        "emoji": "⛄🌻☀️",
        "who": "Olaf",
        "what": "Singing about summer!",
        "where": "Here in the meadow!",
        "when": "In the daytime!",
        "why": "Because he loves the sun!",
        "tag": "Olaf singing about summer",
        "image": "scene_14.png",
        "sentence": "Olaf is singing about summer here in the meadow in the daytime."
    },
    {
        "emoji": "👸🏼❄️🌊",
        "who": "Elsa",
        "what": "Freezing the big waves!",
        "where": "There at the beach!",
        "when": "At stormy night!",
        "why": "To cross the sea!",
        "tag": "Elsa freezing the big waves",
        "image": "scene_15.png",
        "sentence": "Elsa is freezing the big waves there at the beach at stormy night."
    },
    {
        "emoji": "👩🏻🪨🏃‍♀️",
        "who": "Anna",
        "what": "Running away from giants!",
        "where": "There near the dam!",
        "when": "In the morning!",
        "why": "To break the dam!",
        "tag": "Anna running away from giants",
        "image": "scene_16.png",
        "sentence": "Anna is running away from giants there near the dam in the morning."
    },
    {
        "emoji": "👱‍♂️💍🦌",
        "who": "Kristoff",
        "what": "Holding a shiny ring!",
        "where": "Here in the woods!",
        "when": "At sunset!",
        "why": "To marry Anna!",
        "tag": "Kristoff holding a shiny ring",
        "image": "scene_17.png",
        "sentence": "Kristoff is holding a shiny ring here in the woods at sunset."
    },
    {
        "emoji": "🦎❄️👅",
        "who": "Bruni",
        "what": "Catching snowflakes!",
        "where": "Here on the branch!",
        "when": "In the winter morning!",
        "why": "Because it tastes yummy!",
        "tag": "Bruni catching snowflakes",
        "image": "scene_18.png",
        "sentence": "Bruni is catching snowflakes here on the branch in the winter morning."
    },
    {
        "emoji": "👸🏼🎤🏔️",
        "who": "Elsa",
        "what": "Singing loudly!",
        "where": "Here on the castle balcony!",
        "when": "At midnight!",
        "why": "Because she hears a voice!",
        "tag": "Elsa singing loudly",
        "image": "scene_19.png",
        "sentence": "Elsa is singing loudly here on the castle balcony at midnight."
    },
    {
        "emoji": "👩🏻🐎🌲",
        "who": "Anna",
        "what": "Riding a fast horse!",
        "where": "There through the trees!",
        "when": "In the daytime!",
        "why": "To catch up with Elsa!",
        "tag": "Anna riding a fast horse",
        "image": "scene_20.png",
        "sentence": "Anna is riding a fast horse there through the trees in the daytime."
    },
    {
        "emoji": "⛄📚🤓",
        "who": "Olaf",
        "what": "Reading a big book!",
        "where": "Here in the library!",
        "when": "In the afternoon!",
        "why": "To learn new things!",
        "tag": "Olaf reading a big book",
        "image": "scene_21.png",
        "sentence": "Olaf is reading a big book here in the library in the afternoon."
    },
    {
        "emoji": "👸🏼👗❄️",
        "who": "Elsa",
        "what": "Making a new ice dress!",
        "where": "There on the balcony!",
        "when": "At sunrise!",
        "why": "Because she feels happy!",
        "tag": "Elsa making a new ice dress",
        "image": "scene_22.png",
        "sentence": "Elsa is making a new ice dress there on the balcony at sunrise."
    },
    {
        "emoji": "👱‍♂️🪕🎶",
        "who": "Kristoff",
        "what": "Playing his guitar!",
        "where": "Here on the wagon!",
        "when": "At night!",
        "why": "To entertain Sven!",
        "tag": "Kristoff playing his guitar",
        "image": "scene_23.png",
        "sentence": "Kristoff is playing his guitar here on the wagon at night."
    },
    {
        "emoji": "🦌👅🧊",
        "who": "Sven",
        "what": "Licking a cold icicle!",
        "where": "There on the roof!",
        "when": "In the morning!",
        "why": "Because he is silly!",
        "tag": "Sven licking a cold icicle",
        "image": "scene_24.png",
        "sentence": "Sven is licking a cold icicle there on the roof in the morning."
    },
    {
        "emoji": "💂‍♂️🍂🏕️",
        "who": "Mattias and soldiers",
        "what": "Sitting by the fire!",
        "where": "Here in the camp!",
        "when": "At night!",
        "why": "To stay warm!",
        "tag": "Mattias and soldiers sitting by the fire",
        "image": "scene_25.png",
        "sentence": "Mattias and soldiers are sitting by the fire here in the camp at night."
    },
    {
        "emoji": "👸🏼👩🏻🤝",
        "who": "Elsa and Anna",
        "what": "Holding hands!",
        "where": "Here in the courtyard!",
        "when": "In the sunny morning!",
        "why": "Because they love each other!",
        "tag": "Elsa and Anna holding hands",
        "image": "scene_26.png",
        "sentence": "Elsa and Anna are holding hands here in the courtyard in the sunny morning."
    },
    {
        "emoji": "🧌🌿🍄",
        "who": "The little trolls",
        "what": "Rolling like rocks!",
        "where": "There in the valley!",
        "when": "In the afternoon!",
        "why": "To greet Kristoff!",
        "tag": "The little trolls rolling like rocks",
        "image": "scene_27.png",
        "sentence": "The little trolls are rolling like rocks there in the valley in the afternoon."
    },
    {
        "emoji": "🌬️🍃🍂",
        "who": "Gale the wind",
        "what": "Blowing leaves around!",
        "where": "There in the air!",
        "when": "In the breezy afternoon!",
        "why": "To play a game!",
        "tag": "Gale the wind blowing leaves around",
        "image": "scene_28.png",
        "sentence": "Gale the wind is blowing leaves around there in the air in the breezy afternoon."
    },
    {
        "emoji": "🐴💧🌊",
        "who": "The Water Nokk",
        "what": "Swimming fast!",
        "where": "There under the water!",
        "when": "At midnight!",
        "why": "To guard the river!",
        "tag": "The Water Nokk swimming fast",
        "image": "scene_29.png",
        "sentence": "The Water Nokk is swimming fast there under the water at midnight."
    },
    {
        "emoji": "👩🏻⛄🛶",
        "who": "Anna and Olaf",
        "what": "Sliding down the waterfall!",
        "where": "There in the ice cave!",
        "when": "In the daytime!",
        "why": "To escape the dark!",
        "tag": "Anna and Olaf sliding down the waterfall",
        "image": "scene_30.png",
        "sentence": "Anna and Olaf are sliding down the waterfall there in the ice cave in the daytime."
    },
    {
        "emoji": "👸🏼💎❄️",
        "who": "Elsa",
        "what": "Finding the magic crystals!",
        "where": "Here in the sky!",
        "when": "At night!",
        "why": "To save Arendelle!",
        "tag": "Elsa finding the magic crystals",
        "image": "scene_31.png",
        "sentence": "Elsa is finding the magic crystals here in the sky at night."
    },
    {
        "emoji": "👱‍♂️🦌🍎",
        "who": "Kristoff and Sven",
        "what": "Sharing a red apple!",
        "where": "Here in the barn!",
        "when": "In the morning!",
        "why": "Because it is breakfast time!",
        "tag": "Kristoff and Sven sharing a red apple",
        "image": "scene_32.png",
        "sentence": "Kristoff and Sven are sharing a red apple here in the barn in the morning."
    },
    {
        "emoji": "🛖🧖‍♂️🔥",
        "who": "Oaken's family",
        "what": "Saying 'Hoo-hoo'!",
        "where": "Here in the hot sauna!",
        "when": "In the cold evening!",
        "why": "Because they are relaxing!",
        "tag": "Oaken's family saying 'hoo-hoo'",
        "image": "scene_33.png",
        "sentence": "Oaken's family are saying 'hoo-hoo' here in the hot sauna in the cold evening."
    },
    {
        "emoji": "🦎🔥🏃‍♂️",
        "who": "Bruni",
        "what": "Running very fast!",
        "where": "There on the rocks!",
        "when": "In the afternoon!",
        "why": "Because he is excited!",
        "tag": "Bruni running very fast",
        "image": "scene_34.png",
        "sentence": "Bruni is running very fast there on the rocks in the afternoon."
    },
    {
        "emoji": "🪨👣💥",
        "who": "An Earth Giant",
        "what": "Stomping its big feet!",
        "where": "There by the river!",
        "when": "At sunset!",
        "why": "Because it is angry!",
        "tag": "An Earth Giant stomping its big feet",
        "image": "scene_35.png",
        "sentence": "An Earth Giant is stomping its big feet there by the river at sunset."
    },
    {
        "emoji": "👸🏼🐴✨",
        "who": "Elsa",
        "what": "Turning the Nokk to ice!",
        "where": "There on the water!",
        "when": "At sunrise!",
        "why": "To ride to Ahtohallan!",
        "tag": "Elsa turning the nokk to ice",
        "image": "scene_36.png",
        "sentence": "Elsa is turning the nokk to ice there on the water at sunrise."
    },
    {
        "emoji": "👩🏻👑🏰",
        "who": "Anna",
        "what": "Wearing a new crown!",
        "where": "Here in the castle!",
        "when": "In the daytime!",
        "why": "Because she is the new Queen!",
        "tag": "Anna wearing a new crown",
        "image": "scene_37.png",
        "sentence": "Anna is wearing a new crown here in the castle in the daytime."
    },
    {
        "emoji": "⛄❄️🎉",
        "who": "Olaf",
        "what": "Making a snow flurry!",
        "where": "Here in the town square!",
        "when": "In the afternoon!",
        "why": "To make the children smile!",
        "tag": "Olaf making a snow flurry",
        "image": "scene_38.png",
        "sentence": "Olaf is making a snow flurry here in the town square in the afternoon."
    },
    {
        "emoji": "💂‍♂️📜🤔",
        "who": "Mattias",
        "what": "Looking at an old map!",
        "where": "Here in the tent!",
        "when": "In the morning!",
        "why": "To find the way home!",
        "tag": "Mattias looking at an old map",
        "image": "scene_39.png",
        "sentence": "Mattias is looking at an old map here in the tent in the morning."
    },
    {
        "emoji": "👸🏼👩🏻🚢",
        "who": "Elsa and Anna",
        "what": "Looking at a broken ship!",
        "where": "There in the foggy woods!",
        "when": "In the spooky evening!",
        "why": "To find clues!",
        "tag": "Elsa and Anna looking at a broken ship",
        "image": "scene_40.png",
        "sentence": "Elsa and Anna are looking at a broken ship there in the foggy woods in the spooky evening."
    },
    {
        "emoji": "👱‍♂️💍😅",
        "who": "Kristoff",
        "what": "Practicing his proposal!",
        "where": "Here behind a tree!",
        "when": "In the daytime!",
        "why": "Because he is nervous!",
        "tag": "Kristoff practicing his proposal",
        "image": "scene_41.png",
        "sentence": "Kristoff is practicing his proposal here behind a tree in the daytime."
    },
    {
        "emoji": "🦌🛷❄️",
        "who": "Sven",
        "what": "Pulling the heavy sled!",
        "where": "There on the snowy path!",
        "when": "In the morning!",
        "why": "To help his friends travel!",
        "tag": "Sven pulling the heavy sled",
        "image": "scene_42.png",
        "sentence": "Sven is pulling the heavy sled there on the snowy path in the morning."
    },
    {
        "emoji": "🦎❄️😴",
        "who": "Bruni",
        "what": "Sleeping peacefully!",
        "where": "Here in Elsa's hands!",
        "when": "At night!",
        "why": "Because he is cold and safe!",
        "tag": "Bruni sleeping peacefully",
        "image": "scene_43.png",
        "sentence": "Bruni is sleeping peacefully here in elsa's hands at night."
    },
    {
        "emoji": "👸🏼🧊🐎",
        "who": "Elsa",
        "what": "Galloping on the ice horse!",
        "where": "There towards the glacier!",
        "when": "In the bright morning!",
        "why": "To reach the magic river!",
        "tag": "Elsa galloping on the ice horse",
        "image": "scene_44.png",
        "sentence": "Elsa is galloping on the ice horse there towards the glacier in the bright morning."
    },
    {
        "emoji": "👩🏻🗡️🪨",
        "who": "Anna",
        "what": "Waving a sword!",
        "where": "There by the rocky shore!",
        "when": "At twilight!",
        "why": "To get the giants' attention!",
        "tag": "Anna waving a sword",
        "image": "scene_45.png",
        "sentence": "Anna is waving a sword there by the rocky shore at twilight."
    },
    {
        "emoji": "⛄🍂🏃‍♂️",
        "who": "Olaf",
        "what": "Running away from the wind!",
        "where": "Here in the clearing!",
        "when": "In the windy afternoon!",
        "why": "Because Gale is tickling him!",
        "tag": "Olaf running away from the wind",
        "image": "scene_46.png",
        "sentence": "Olaf is running away from the wind here in the clearing in the windy afternoon."
    },
    {
        "emoji": "💂‍♂️📸😲",
        "who": "Mattias",
        "what": "Looking at a photograph!",
        "where": "Here in the forest!",
        "when": "In the daytime!",
        "why": "Because he has never seen one!",
        "tag": "Mattias looking at a photograph",
        "image": "scene_47.png",
        "sentence": "Mattias is looking at a photograph here in the forest in the daytime."
    },
    {
        "emoji": "👸🏼👩🏻⛄👱‍♂️🦌",
        "who": "Everyone together",
        "what": "Having a picnic!",
        "where": "Here on the blanket!",
        "when": "In the sunny afternoon!",
        "why": "To celebrate being a family!",
        "tag": "Everyone together having a picnic",
        "image": "scene_48.png",
        "sentence": "Everyone together are having a picnic here on the blanket in the sunny afternoon."
    },
    {
        "emoji": "👑👸🏼👩🏻",
        "who": "King Agnarr",
        "what": "Telling a bedtime story!",
        "where": "Here in the girls' room!",
        "when": "At night!",
        "why": "To teach them about the forest!",
        "tag": "King Agnarr telling a bedtime story",
        "image": "scene_49.png",
        "sentence": "King Agnarr is telling a bedtime story here in the girls' room at night."
    }
];